import Header from "@/components/Header";
import "./globals.css";
import { Kumbh_Sans } from "next/font/google";
import CartContextProvider from "@/components/StateContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={kumbhSans.className}>
      <body>
        <CartContextProvider>
          <Header />
          <main>{children}</main>
        </CartContextProvider>
      </body>
    </html>
  );
}
